name: Deploy to remote server
env:
  ACTIONS_RUNNER_DEBUG: true
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-home-cache-cleanup: true

      - name: Grant execute permission for gradlew
        working-directory: ./todo
        run: chmod +x ./gradlew

      - name: Run build with Gradle Wrapper
        working-directory: ./todo
        run: ./gradlew clean build -x test
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Send files to the server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          source: "todo/scripts/deploy.sh,todo/builds/libs/*.jar"
          target: "/home/${{ secrets.USER }}/download/todo"
          strip_components: 2

      - name: Deploy remote ssh commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script_stop: true
          script: |
            chmod +x /home/${{ secrets.USER }}/download/todo/deploy.sh
            sh /home/${{ secrets.USER }}/download/todo/deploy.sh