name: Deploy to remote server

env:
 ACTIONS_RUNNER_DEBUG: true

on:
 push:
   branches: [ "main" ]
 pull_request:
   branches: [ "main" ]

jobs:
 build:
   runs-on: ubuntu-latest
   
   steps:
     - uses: actions/checkout@v3
     
     - name: Set Java
       uses: actions/setup-java@v3
       with:
         java-version: '17'
         distribution: 'temurin'
     
     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2
       with:
         gradle-home-cache-cleanup: true
         
     - name: Grant execute permission for gradlew
       working-directory: ./todo
       run: chmod +x ./gradlew
       
     - name: Run build with Gradle Wrapper
       working-directory: ./todo
       run: ./gradlew clean build -x test

 deploy:
   runs-on: ubuntu-latest
   
   steps:
     - name: Send files to the server
       uses: appleboy/scp-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER }} 
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         source: "todo/scripts/deploy.sh,todo/builds/libs/todo-0.0.1-SNAPSHOT.jar"
         target: "/home/${{ secrets.USER }}/download"
         strip_components: 1
         
     - name: Deploy remote ssh commands using password
       uses: appleboy/scp-action@master
       with:
         host: ${{ secrets.HOST }}
         username: ${{ secrets.USER }}
         password: ${{ secrets.PASSWORD }}
         port: ${{ secrets.SSH_PORT }}
         script_stop: true
         script: |
           mkdir -p /home/${{ secrets.USER }}/deploy
           chmod +x /home/${{ secrets.USER }}/download/deploy.sh
           sh /home/${{ secrets.USER }}/download/deploy.sh
